---
# Ansible playbook for setting up a virtual machine
- name: My first play
  hosts: all,localhost
  vars_files:
    - values.yml
  tasks:
    - ansible.builtin.include_tasks:
        file: ansible/snap.yml
    - ansible.builtin.include_tasks:
        file: ansible/chrome.yml
    - ansible.builtin.include_tasks:
        file: ansible/vscode.yml
    - ansible.builtin.include_tasks:
        file: ansible/java.yml
